version: "3.8"

services:
  tts-api:
    build:
      context: ./TTS
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  stt-api:
    build:
      context: ./STT
      dockerfile: Dockerfile.api
    ports:
      - "8001:8000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  sound-generator-api:
    build:
      context: ./sound_generator
      dockerfile: Dockerfile.api
    ports:
      - "8002:8000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
